# Changes here will be overwritten by Copier
_commit: 08e42af
_src_path: https://github.com/monarch-initiative/monarch-project-copier
copyright_year: '2025'
email: justinreese@lbl.gov
full_name: Justin Reese
gh_action_docs_preview: true
github_handle: justaddcoffee
github_org: justaddcoffee
license: BSD-3-Clause
project_description: Classifier that uses embeddings to find useful paths between
    drugs and disease
project_name: path-embedding
project_slug: path_embedding

